Other bash scripts

diff --git a/s3/bash-scripts/sync b/s3/bash-scripts/sync
--- a/s3/bash-scripts/sync
+++ b/s3/bash-scripts/sync
@@ -1,1 +1,41 @@
 #!/usr/bin/env bash
+
+echo "=== sync object"
+
+# exit immediately if any command returns a non-zero status
+set -e
+
+# Check for bucket name
+if [ -z "$1" ]; then
+    echo "There needs to be a bucket name eg. ./bucket my-bucekt-name"
+    exit 1
+fi
+
+# Check for bucket name
+if [ -z "$2" ]; then
+    echo "There needs to be a bucket name eg. ./bucket my-bucekt-name"
+    exit 1
+fi
+
+BUCKET_NAME=$1
+FILENAME_PREFIX=$2
+
+# Store files in a subfolder of the current directory
+OUTPUT_DIR="./s3-bash-scripts"
+
+rm -r $OUTPUT_DIR
+
+# Create the output folder relative to where you run the script
+mkdir -p "$OUTPUT_DIR"
+
+# Generate a random number between 5 and 10
+NUM_FILES=$((RANDOM % 6 + 5))
+
+for ((i=1; i<=NUM_FILES; i++)); do
+    FILENAME="$OUTPUT_DIR/$FILENAME_PREFIX_$i.txt"
+    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
+done
+
+echo "Created $NUM_FILES files in $OUTPUT_DIR"
+
+aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files
